version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100

  strapi:
    build: ./backend
    ports:
      - '1337:1337'
    volumes:
      - ./backend:/usr/src/app
    environment:
      - DATABASE_CLIENT=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - DATABASE_NAME=strapi_db
      - DATABASE_USERNAME=strapi_user
      - DATABASE_PASSWORD=strapi_password
      - CHOKIDAR_USEPOLLING=true
      - CHOKIDAR_INTERVAL=100
    depends_on:
      - db

  db:
    image: postgres:15
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=strapi_db
      - POSTGRES_USER=strapi_user
      - POSTGRES_PASSWORD=strapi_password
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
